name: drivechain_client
description:
  "A frontend for interacting with a Drivechain-enabled layer 1 bitcoin network."
publish_to: "none"

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.4.3
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  grpc: ^4.0.1
  sail_ui:
    path: ../sail_ui
  logger: ^2.4.0
  google_fonts: ^6.2.1
  auto_route: ^9.2.2
  fixnum: ^1.1.0
  shared_preferences: ^2.3.2
  get_it: ^7.7.0
  meta: ^1.15.0
  protobuf: ^3.1.0
  dotted_border: ^2.1.0
  money2: ^5.2.1
  super_clipboard: ^0.8.22
  window_manager: ^0.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
