# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: pub
    directory: "/packages/sidesail"
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: "/packages/sail_ui"
    schedule:
      interval: weekly
