name: sail_ui
description: SideSail Design System
version: 0.0.1
publish_to: none

environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=1.17.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_custom_tabs: ^2.1.0
    flutter_svg: ^2.0.10+1
    flutter_platform_alert: ^0.5.3
    intl: ^0.19.0
    crypto: ^3.0.5
    logger: ^2.4.0
    shared_preferences: ^2.3.2
    auto_route: ^9.2.2
    get_it: ^8.0.0
    collection: ^1.18.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    assets:
        - assets/svgs/
        - assets/pngs/
