name: sidesail
description: UI for Drivechain (BIP300/301) based sidechains
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.13.9

dependencies:
  flutter:
    sdk: flutter
  sail_ui:
    path: ../sail_ui

  cupertino_icons: ^1.0.8
  dart_coin_rpc:
    git:
      url: https://github.com/barebitcoin/dart_coin_rpc.git
      # master, as of 08.06.2024
      ref: ab0b7cb2de6e1634a6e65892770ed0d157d38443
  flutter_highlighter: ^0.1.1
  logger: ^2.3.0
  dio: ^5.5.0+1
  auto_route: ^8.3.0
  get_it: ^7.7.0
  collection: ^1.18.0
  stacked: ^3.4.3
  intl: ^0.19.0
  web3dart:
    git:
      url: https://github.com/xclud/web3dart.git
      ref: main
    version: 2.7.3
  http: ^1.2.1
  path_provider: ^2.1.3
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  flutter_window_close: ^1.0.0

# Needed for silencing complaints from adding the web3dart lib
dependency_overrides:
  stream_channel: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  msix: ^3.16.7

flutter:
  uses-material-design: true

  assets:
    - assets/bin/

  fonts:
    - family: Inter
      fonts:
        - asset: ./assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: ./assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: ./assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: ./assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: ./assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: ./assets/fonts/Inter-Black.ttf
          weight: 700

    - family: SourceCodePro
      fonts:
        - asset: ./assets/fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: ./assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: ./assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: ./assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: ./assets/fonts/SourceCodePro-Bold.ttf
          weight: 600
        - asset: ./assets/fonts/SourceCodePro-Black.ttf
          weight: 700

        - asset: ./assets/fonts/SourceCodePro-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: ./assets/fonts/SourceCodePro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: ./assets/fonts/SourceCodePro-Italic.ttf
          style: italic
          weight: 400
        - asset: ./assets/fonts/SourceCodePro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: ./assets/fonts/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: ./assets/fonts/SourceCodePro-BlackItalic.ttf
          style: italic
          weight: 600

# Windows release stuff.
# This currently relies on having a self-signed certificate
# locally available, which must be changed before this is
# properly deployed (either published to the MS store or 
# as an installer on a website somewhere).
# https://pub.dev/packages/msix
msix_config:
  display_name: SideSail
  languages: en-us
  windows_build_args: --dart-define-from-file=build-vars.env
  publisher_display_name: LayerTwo Labs
  identity_name: com.layertwolabs.sidesail
  logo_path: logo.png
  capabilities: internetClientServer
  output_name: SideSail
  install_certificate: false
  certificate_path: CERTIFICATE.pfx
  certificate_password: ""