name: faucet
description: "a drivechain faucet"
publish_to: "none"

version: 1.0.0

environment:
  sdk: 3.10.0
  flutter: 3.38.1

dependencies:
  flutter:
    sdk: flutter
  # internal packages
  sail_ui:
    path: ../sail_ui

  auto_route: ^10.3.0
  fixnum: ^1.1.1
  cupertino_icons: ^1.0.8
  stacked: ^3.5.0
  get_it: ^8.3.0
  logger: ^2.6.2
  http: ^1.6.0
  intl: ^0.20.2
  protobuf: ^4.2.0
  meta: ^1.17.0
  connectrpc: ^1.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.10.3

  auto_route_generator: ^10.2.6
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
