name: drivechain_lints
description: Custom lint rules for drivechain frontends
version: 0.0.1
publish_to: none

environment:
  sdk: 3.10.8
  flutter: 3.38.9

dependencies:
  analyzer: ">=7.3.0 <11.0.0"
  analyzer_plugin: ">=0.12.0 <1.0.0"
  custom_lint_builder: ^0.8.0

dev_dependencies:
  custom_lint: ^0.8.0
