name: sail_ui
description: SideSail Design System
version: 0.0.1
publish_to: none

environment:
  sdk: 3.11.0
  flutter: 3.41.2

dependencies:
  dart_coin_rpc:
    git:
      url: https://github.com/barebitcoin/dart_coin_rpc.git
      # master, as of 08.06.2024
      ref: ab0b7cb2de6e1634a6e65892770ed0d157d38443
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.4.1
  flutter_svg: ^2.2.3
  dio: 5.9.0
  fixnum: ^1.1.1
  path: ^1.9.1
  archive: ^4.0.7
  intl: ^0.20.2
  crypto: ^3.0.7
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  bip39_mnemonic: ^4.0.1
  dart_bip32_bip44: ^0.2.0
  logger: ^2.6.2
  stacked: ^3.5.0
  skeletonizer: ^2.1.1
  auto_route: ^11.1.0
  get_it: ^8.3.0
  collection: ^1.19.1
  path_provider: ^2.1.5
  synchronized: ^3.4.0
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  connectrpc: 1.0.0
  convert: ^3.1.2
  desktop_multi_window:
    git:
      url: https://github.com/octobocto/flutter-plugins.git
      ref: 252f3f7910288500039c39ae2b944622a0e55152
      path: packages/desktop_multi_window
  window_manager: ^0.5.1
  web: ^1.1.1
  thirds: ^0.2.0-alpha.1
  xterm: ^4.0.0
  flutter_pty: ^0.4.2

  file_picker: ^10.3.7
  http: ^1.6.0
  uuid: ^4.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  drivechain_lints:
    path: ../drivechain_lints
  auto_route_generator: ^10.4.0
  build_runner: ^2.11.1

flutter:
  assets:
    - assets/svgs/
    - assets/pngs/
